stages:
  - test
  - build
  - deploy

docs-build:
  stage: build
  image:
    name: python:latest
  script:
    - pip install -e.[docs]
    - mkdocs build --site-dir build/docs/public
  artifacts:
    paths:
      - build/docs/public
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    changes:
      paths:
        - docs/*

docs-deploy:
  stage: deploy
  image: alpine
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$WWW_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - scp -o StrictHostKeyChecking=no -r build/docs/public deploy-www@atopile.io:/var/www/docs
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        paths:
          - docs/*

docker-ci-build:
  stage: build
  image:
    # consider upgrading to a newer version of kaniko?
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - export CI_COMMIT_TAG="v0.0.0.dummy"
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/dockerfiles/Dockerfile.ci"
      --destination "${CI_REGISTRY_IMAGE}/ci:latest"
      --destination "${CI_REGISTRY_IMAGE}/ci:$CI_COMMIT_TAG"
      --build-arg SETUPTOOLS_SCM_PRETEND_VERSION="$CI_COMMIT_TAG"
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/dockerfiles/Dockerfile.dev"
      --destination "${CI_REGISTRY_IMAGE}/dev:latest"
      --destination "${CI_REGISTRY_IMAGE}/dev:$CI_COMMIT_TAG"
      --build-arg SETUPTOOLS_SCM_PRETEND_VERSION="$CI_COMMIT_TAG"
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/dockerfiles/Dockerfile.user"
      --destination "${CI_REGISTRY_IMAGE}/user:latest"
      --destination "${CI_REGISTRY_IMAGE}/user:$CI_COMMIT_TAG"
      --build-arg SETUPTOOLS_SCM_PRETEND_VERSION="$CI_COMMIT_TAG"
  # rules:
  #   - if: $CI_COMMIT_TAG

viewer-test:
  stage: test
  image: node:latest
  script:
    - npm ci
    - npm run test

viewer-build:
  stage: build
  image: node:latest
  script:
    - npm ci
    - npm run build

cli-lint:
  stage: test
  image: python:latest
  script:
    - pip install -e ."[dev,test,docs]"
    - ruff src/atopile

cli-test:
  stage: test
  image: python:latest
  script:
    - pip install -e ."[dev,test,docs]"
    - pytest
  artifacts:
    paths:
      - artifacts

cli-build:
  stage: build
  image: python:latest
  script:
    - pip install build twine
    - python -m build
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  rules:
    - if: $CI_COMMIT_TAG

extension-build:
  stage: deploy
  image: node:latest
  script:
    - npm install -g @vscode/vsce
    - cd src/vscode-atopile
    - vsce package --pre-release
  artifacts:
    paths:
      - src/vscode-atopile/atopile-*.vsix
  rules:
    - changes:
        paths:
          - src/vscode-atopile/*
